# botの設定値を置くファイルです。
# yaml形式で記載しています。わかんない場合はググってください

# botのtoken
discord_bot_token: "でぃすこーどのとーくん"

# 対象になるサーバ(=Guild)のID
target_guild_id: 00000000

# クラメン全員についているロールのID
# このロールがついている人のみ、クラメンとみなします。
# 人数チェックはしていないので、100人であろうが、0人であろうが関係になしに動きます。
target_role_id: 00000000

# 凸管理コマンドが実行できるチャンネルのID
attack_management_channel_id: 00000000

# 凸状況一覧表を投稿するチャンネルのID
attack_status_channel_id: 000000